// Config
@TodoApi_HostAddress = https://localhost:7083
@id=1
@page=1
@pageSize=20
@IsCompleted=true
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc1ODExMjQ5OSwiaXNzIjoiVG9kb0FwcCIsImF1ZCI6IlRvZG9Vc2VycyJ9.ESCB34XIVHcRrJS3sy2lfnAbkoKxnxDrG6ocxTIoXPI


// USE THIS ONE FIRST TO GET A TOKEN
// THEN REPLACE THE TOKEN IN THE CONFIG ABOVE
// Either use admin or user,
// Username: admin
// Password: admin123
// Or use the user,
// Username: user
// Password: user123
###

POST {{TodoApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "Username": "admin",
  "Password": "admin123"
}

###



// Requests
// Change a todo via a id use GET first to find id
PUT {{TodoApi_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": {{id}},
  "name": "Test5billion",
  "IsCompleted": true
}

###


// Delete a todo with id
DELETE {{TodoApi_HostAddress}}/api/todoitems/{{id}}
Authorization: Bearer {{token}}

###


// Possible flags are 
// page       : any number above 0               : page={{page}}
// pageSize   : amount of results from each page : pageSize={{pageSize}}
// isCompleted: either null,false or true        : isCompleted={{isCompleted}}
GET {{TodoApi_HostAddress}}/api/todoitems/

###


// Make a new todo
// name        : Name the todo                         : Any value
// IsCompleted : Has the do been completed             : true or false
// Token       : Auth header for admin needed actions  : Get the value using the post request to /auth/login
POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test5billion",
  "IsCompleted": false
}

###